---
micronaut:
    application:
        name: wada
                
#Uncomment to set server port
#    server:
#        port: 8080

mongodb:
    uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"
endpoints:
    health:
        enabled: true
    info:
        enabled: true
        sensitive: false

wada:
    databaseName: "test"
    collectionName: "messages"